apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: health-insight-ventures
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/max-scale: "100"
        run.googleapis.com/min-scale: "1"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/health-insight-ventures:latest
        ports:
        - name: http1
          containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: DATABASE_URL
              key: latest
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: OPENAI_API_KEY
              key: latest
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: SENDGRID_API_KEY
              key: latest
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: TWILIO_ACCOUNT_SID
              key: latest
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: TWILIO_AUTH_TOKEN
              key: latest
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: TWILIO_PHONE_NUMBER
              key: latest
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5