name: terraform-dev

on:
  push:
    branches: [ "dev" ]

jobs:
  apply-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform init (uses backend if present)
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform workspace (dev)
        working-directory: terraform
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Terraform apply (dev)
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var enable_network=true \
            -var enable_service_account=true

