name: terraform-prod

on:
  push:
    branches: [ "prod" ]

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform init (uses backend if present)
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform workspace (prod)
        working-directory: terraform
        run: |
          terraform workspace select prod || terraform workspace new prod

      - name: Terraform plan (prod)
        working-directory: terraform
        run: terraform plan -input=false -no-color

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    env:
      TF_IN_AUTOMATION: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform workspace (prod)
        working-directory: terraform
        run: |
          terraform workspace select prod || terraform workspace new prod

      - name: Terraform apply (prod)
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var enable_network=true \
            -var enable_service_account=true

